Update download

diff --git a/scripts/download b/scripts/download
--- a/scripts/download
+++ b/scripts/download
@@ -13,23 +13,23 @@ if [ "${platform}" == "linux" ]; then
     if [ "${arch}" == "x86_64" ]; then
         tarball_name="mynt-${version}-lin64.tar.gz"
     elif [ "${arch}" == "x86_32" ]; then
-        tarball_name="mynt-${version}-lin32.tar.gz"
+        tarball_name="mynt-${version}-lin64.tar.gz"
     fi
 elif [ "${platform}" == "darwin" ]; then
-    tarball_name="mynt-${version}-osx64.tar.gz"
+    tarball_name="mynt-${version}-lin32.tar.g"
 else
-    echo "Myntcoin binary distribution not available for platform and architecture"
+    echo "Mynt binary distribution not available for platform and architecture"
     exit -1
 fi
 
 binary_url="${url}/${tag}/${tarball_name}"
-shasums_url="${url}/${tag}/SHA256SUMS.asc"
-
+#shasums_url="${url}/${tag}/SHA256SUMS.asc"
+echo "${root_dir}/bin"
 download_myntd() {
 
     cd "${root_dir}/bin"
 
-    echo "Downloading myntcoin: ${binary_url}"
+    echo "Downloading mynt: ${binary_url}"
 
     is_curl=true
     if hash curl 2>/dev/null; then
@@ -42,13 +42,13 @@ download_myntd() {
     if test $? -eq 0; then
         if [ "${is_curl}" = true ]; then
             curl -L $binary_url > $tarball_name
-            curl -L $shasums_url > SHA256SUMS.asc
+            #curl -L $shasums_url > SHA256SUMS.asc
         else
             wget $binary_url
-            wget $shasums_url
+            #wget $shasums_url
         fi
         if test -e "${tarball_name}"; then
-            echo "Unpacking myntcoin distribution"
+            echo "Unpacking Mynt distribution"
             tar -xvzf $tarball_name
             if test $? -eq 0; then
                 ln -sf "mynt-${version}/bin/myntd"
@@ -56,40 +56,40 @@ download_myntd() {
             fi
         fi
     fi
-    echo "Myntoin binary distribution could not be downloaded"
+    echo "Mynt binary distribution could not be downloaded"
     exit -1
 }
 
-verify_download() {
-    echo "Verifying signatures of myntcoin download"
-    gpg --verify "${root_dir}/bin/SHA256SUMS.asc"
+#verify_download() {
+ #   echo "Verifying signatures of Mynt download"
+  #  gpg --verify "${root_dir}/bin/SHA256SUMS.asc"
+#
+ #   if hash shasum 2>/dev/null; then
+  #      shasum_cmd="shasum -a 256"
+   # else
+    #    shasum_cmd="sha256sum"
+    #fi
 
-    if hash shasum 2>/dev/null; then
-        shasum_cmd="shasum -a 256"
-    else
-        shasum_cmd="sha256sum"
-    fi
-
-    download_sha=$(${shasum_cmd} "${root_dir}/bin/${tarball_name}" | awk '{print $1}')
-    expected_sha=$(cat "${root_dir}/bin/SHA256SUMS.asc" | grep "${tarball_name}" | awk '{print $1}')
-    echo "Checksum (download): ${download_sha}"
-    echo "Checksum (verified): ${expected_sha}"
-    if [ "${download_sha}" != "${expected_sha}" ]; then
-        echo -e "\033[1;31mChecksums did NOT match!\033[0m\n"
-        exit 1
-    else
-        echo -e "\033[1;32mChecksums matched!\033[0m\n"
-    fi
-}
+    #download_sha=$(${shasum_cmd} "${root_dir}/bin/${tarball_name}" | awk '{print $1}')
+    #expected_sha=$(cat "${root_dir}/bin/SHA256SUMS.asc" | grep "${tarball_name}" | awk '{print $1}')
+    #echo "Checksum (download): ${download_sha}"
+    #echo "Checksum (verified): ${expected_sha}"
+    #if [ "${download_sha}" != "${expected_sha}" ]; then
+     #   echo -e "\033[1;31mChecksums did NOT match!\033[0m\n"
+     #   exit 1
+    #else
+     #   echo -e "\033[1;32mChecksums matched!\033[0m\n"
+   # fi
+#}
 
 download=1
 verify=0
 
-if [ "${SKIP_MYNTCOIN_DOWNLOAD}" = 1 ]; then
+if [ "${SKIP_MYNT_DOWNLOAD}" = 1 ]; then
     download=0;
 fi
 
-if [ "${VERIFY_MYNTCOIN_DOWNLOAD}" = 1 ]; then
+if [ "${VERIFY_MYNT_DOWNLOAD}" = 1 ]; then
     verify=1;
 fi
 
@@ -98,10 +98,10 @@ while [ -n "$1" ]; do
   value="$2"
 
   case $param in
-    --skip-myntcoin-download)
+    --skip-mynt-download)
           download=0
           ;;
-    --verify-myntcoin-download)
+    --verify-mynt-download)
           verify=1
           ;;
   esac
